'use client'

import { useMemo, useState } from 'react'
import { Layout, Zap } from 'lucide-react'
import type {
  ContentPiece,
  CustomField,
  Platform,
  Program,
  Stage,
  Trigger,
} from '@/lib/content-data'
import {
  APPROVERS,
  CONTENT_PIECES,
  STAGES,
  TRIGGERS,
  nextPieceId,
} from '@/lib/content-data'
import {
  AI_MODEL_LABEL,
  generateMockMetrics,
  generateVariantCopy,
} from '@/lib/mock-ai'
import { GuidedTour } from '@/components/salon/guided-tour'
import { KanbanColumn } from '@/components/salon/kanban-column'
import { NewFlowModal } from '@/components/salon/new-flow-modal'
import { TopBar } from '@/components/salon/top-bar'
import { TriggersPanel } from '@/components/salon/triggers-panel'
import { VersionPanel } from '@/components/salon/version-panel'
import { WelcomeScreen } from '@/components/salon/welcome-screen'

const NEXT_STAGE: Partial<Record<Stage, Stage>> = {
  creacion: 'revision',
  revision: 'aprobado',
  aprobado: 'publicado',
}

export default function SalonDeContenido() {
  const [screen, setScreen] = useState<'welcome' | 'dashboard'>('welcome')
  const [tourActive, setTourActive] = useState(false)
  const [pieces, setPieces] = useState<ContentPiece[]>(CONTENT_PIECES)
  const [platformFilter, setPlatformFilter] = useState<Platform | null>(null)
  const [programFilter, setProgramFilter] = useState<Program | null>(null)
  const [stageFilter, setStageFilter] = useState<Stage | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [newFlowOpen, setNewFlowOpen] = useState(false)
  const [view, setView] = useState<'board' | 'triggers'>('board')
  const [triggers, setTriggers] = useState<Trigger[]>(TRIGGERS)

  const filtered = useMemo(
    () =>
      pieces.filter(
        (p) =>
          (platformFilter === null || p.platform === platformFilter) &&
          (programFilter === null || p.program === programFilter),
      ),
    [pieces, platformFilter, programFilter],
  )

  const counts = useMemo(() => {
    const c: Record<Stage, number> = {
      creacion: 0,
      revision: 0,
      aprobado: 0,
      publicado: 0,
    }
    for (const p of filtered) c[p.stage]++
    return c
  }, [filtered])

  const visibleStages = stageFilter
    ? STAGES.filter((s) => s.id === stageFilter)
    : STAGES

  const selected = selectedId
    ? (pieces.find((p) => p.id === selectedId) ?? null)
    : null

  function handleTrigger(piece: ContentPiece) {
    const next = NEXT_STAGE[piece.stage]
    if (!next) return

    let updated = pieces.map((p) =>
      p.id === piece.id
        ? {
            ...p,
            stage: next,
            ...(next === 'publicado'
              ? {
                  publishedAt: new Date().toISOString(),
                  metrics: p.metrics ?? generateMockMetrics(),
                }
              : {}),
          }
        : p,
    )

    if (next === 'aprobado') {
      const platformTrigger = triggers.find((t) => t.id === 'tr1')
      const abTrigger = triggers.find((t) => t.id === 'tr2')

      let firedTrigger: Trigger | undefined
      let variantPlatform: Platform = piece.platform
      let kind: 'platform-variant' | 'ab-variants' | undefined

      if (piece.platform === 'instagram' && platformTrigger?.active) {
        firedTrigger = platformTrigger
        kind = 'platform-variant'
        variantPlatform = 'linkedin'
      } else if (abTrigger?.active) {
        firedTrigger = abTrigger
        kind = 'ab-variants'
      }

      if (firedTrigger && kind) {
        const now = new Date()
        const autoPiece: ContentPiece = {
          id: nextPieceId(updated),
          title:
            kind === 'platform-variant'
              ? `Variante LinkedIn — ${piece.title}`
              : `Variante A/B — ${piece.title}`,
          stage: 'creacion',
          platform: variantPlatform,
          assetType: 'copy',
          program: piece.program,
          copyPreview: generateVariantCopy(piece.title, kind),
          generatedBy: AI_MODEL_LABEL,
          approver: piece.approver,
          createdAt: now.toISOString(),
          customFields: [
            {
              id: `f${Date.now()}`,
              label: 'Disparador',
              value: firedTrigger.name,
            },
          ],
          versions: [
            {
              id: 'v1',
              label: 'v1 — generado por disparador',
              timestamp: now.toLocaleString('es-MX', {
                day: '2-digit',
                month: 'short',
                hour: '2-digit',
                minute: '2-digit',
              }),
              author: AI_MODEL_LABEL,
              note: `Generado automáticamente por el disparador "${firedTrigger.name}" al aprobarse ${piece.id}.`,
            },
          ],
          autoGenerated: true,
        }

        updated = [autoPiece, ...updated]

        const firedId = firedTrigger.id
        setTriggers((prevT) =>
          prevT.map((t) =>
            t.id === firedId ? { ...t, runCount: t.runCount + 1 } : t,
          ),
        )
      }
    }

    setPieces(updated)
  }

  function handleToggleTrigger(id: string) {
    setTriggers((prev) =>
      prev.map((t) => (t.id === id ? { ...t, active: !t.active } : t)),
    )
  }

  function handleCreateFlow(input: {
    brief: string
    platform: Platform
    program: Program
    copy: string
  }) {
    const id = nextPieceId(pieces)
    const now = new Date()
    const approver = APPROVERS[Math.floor(Math.random() * APPROVERS.length)]
    const title =
      input.brief.length > 64 ? `${input.brief.slice(0, 61)}...` : input.brief

    const newPiece: ContentPiece = {
      id,
      title,
      stage: 'creacion',
      platform: input.platform,
      assetType: 'copy',
      program: input.program,
      copyPreview: input.copy,
      generatedBy: AI_MODEL_LABEL,
      approver,
      createdAt: now.toISOString(),
      customFields: [
        { id: `f${Date.now()}`, label: 'Brief', value: input.brief },
      ],
      versions: [
        {
          id: 'v1',
          label: 'v1 — generado por IA',
          timestamp: now.toLocaleString('es-MX', {
            day: '2-digit',
            month: 'short',
            hour: '2-digit',
            minute: '2-digit',
          }),
          author: AI_MODEL_LABEL,
          note: 'Copy generado automáticamente a partir del brief. Pendiente de edición y revisión humana.',
        },
      ],
    }

    setPieces((prev) => [newPiece, ...prev])
    setNewFlowOpen(false)
  }

  function handleEditCopy(pieceId: string, copy: string) {
    setPieces((prev) =>
      prev.map((p) => (p.id === pieceId ? { ...p, copyPreview: copy } : p)),
    )
  }

  function handleAddField(pieceId: string, field: Omit<CustomField, 'id'>) {
    setPieces((prev) =>
      prev.map((p) =>
        p.id === pieceId
          ? {
              ...p,
              customFields: [
                ...p.customFields,
                { ...field, id: `f${Date.now()}` },
              ],
            }
          : p,
      ),
    )
  }

  if (screen === 'welcome') {
    return (
      <WelcomeScreen
        onNormal={() => setScreen('dashboard')}
        onTour={() => {
          setScreen('dashboard')
          setTourActive(true)
        }}
      />
    )
  }

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <TopBar
        platformFilter={platformFilter}
        programFilter={programFilter}
        stageFilter={stageFilter}
        counts={counts}
        onPlatformFilter={setPlatformFilter}
        onProgramFilter={setProgramFilter}
        onStageFilter={setStageFilter}
        onNewFlow={() => setNewFlowOpen(true)}
      />

      <nav
        aria-label="Vista"
        className="flex items-center gap-1 border-b border-border bg-background px-4 py-2 md:px-6"
      >
        <button
          type="button"
          onClick={() => setView('board')}
          aria-pressed={view === 'board'}
          className={`flex items-center gap-1.5 rounded px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-wider transition-colors ${
            view === 'board'
              ? 'bg-secondary text-foreground'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          <Layout className="size-3.5" aria-hidden="true" />
          Tablero
        </button>
        <button
          type="button"
          data-tour="triggers-tab"
          onClick={() => setView('triggers')}
          aria-pressed={view === 'triggers'}
          className={`flex items-center gap-1.5 rounded px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-wider transition-colors ${
            view === 'triggers'
              ? 'bg-secondary text-foreground'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          <Zap className="size-3.5" aria-hidden="true" />
          Disparadores
        </button>
      </nav>

      {view === 'board' ? (
        <main className="flex-1 p-4 md:p-6">
          <div
            data-tour="board"
            className="flex gap-4 overflow-x-auto pb-4 md:grid md:grid-cols-2 md:overflow-visible lg:flex lg:overflow-visible"
          >
            {visibleStages.map((stage) => (
              <KanbanColumn
                key={stage.id}
                stage={stage.id}
                pieces={filtered.filter((p) => p.stage === stage.id)}
                onSelect={(p) => setSelectedId(p.id)}
                onTrigger={handleTrigger}
                onAddField={handleAddField}
                onEditCopy={handleEditCopy}
              />
            ))}
          </div>
        </main>
      ) : (
        <main className="flex-1">
          <TriggersPanel triggers={triggers} onToggle={handleToggleTrigger} />
        </main>
      )}

      {selected && (
        <VersionPanel piece={selected} onClose={() => setSelectedId(null)} />
      )}

      {newFlowOpen && (
        <NewFlowModal
          onClose={() => setNewFlowOpen(false)}
          onCreate={handleCreateFlow}
        />
      )}

      {tourActive && <GuidedTour onFinish={() => setTourActive(false)} />}
    </div>
  )
}
